// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ServiceLocator.tt
using WPAppStudio.Ioc;
using WPAppStudio.Ioc.Interfaces;
using WPAppStudio.ViewModel;
using WPAppStudio.ViewModel.Interfaces;

namespace WPAppStudio.Services
{
    /// <summary>
    /// Implementation of the ViewModel locator service based on IoC.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public class ViewModelLocatorService
    {
        // IoC container
        private readonly IContainer _container;

        /// <summary>
        /// Initializes a new instance of the <see cref="ViewModelLocatorService" /> class.
        /// </summary>
        public ViewModelLocatorService()
        {
            _container = new Container();
        }

        /// <summary>
        /// Gets the reference to a info_InfoViewModel.
        /// </summary>
		public Iinfo_InfoViewModel info_InfoViewModel
        {
            get { return _container.Resolve<info_InfoViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a PhotoAlbum_DetailViewModel.
        /// </summary>
		public IPhotoAlbum_DetailViewModel PhotoAlbum_DetailViewModel
        {
            get { return _container.Resolve<PhotoAlbum_DetailViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a SpecialPlaces_DetailViewModel.
        /// </summary>
		public ISpecialPlaces_DetailViewModel SpecialPlaces_DetailViewModel
        {
            get { return _container.Resolve<SpecialPlaces_DetailViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a monuments_DetailViewModel.
        /// </summary>
		public Imonuments_DetailViewModel monuments_DetailViewModel
        {
            get { return _container.Resolve<monuments_DetailViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a TravelToMeerut_InfoViewModel.
        /// </summary>
		public ITravelToMeerut_InfoViewModel TravelToMeerut_InfoViewModel
        {
            get { return _container.Resolve<TravelToMeerut_InfoViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a Weather_InfoViewModel.
        /// </summary>
		public IWeather_InfoViewModel Weather_InfoViewModel
        {
            get { return _container.Resolve<Weather_InfoViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a Etymology_InfoViewModel.
        /// </summary>
		public IEtymology_InfoViewModel Etymology_InfoViewModel
        {
            get { return _container.Resolve<Etymology_InfoViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a Mythology_InfoViewModel.
        /// </summary>
		public IMythology_InfoViewModel Mythology_InfoViewModel
        {
            get { return _container.Resolve<Mythology_InfoViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a Geography_InfoViewModel.
        /// </summary>
		public IGeography_InfoViewModel Geography_InfoViewModel
        {
            get { return _container.Resolve<Geography_InfoViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a Economy_InfoViewModel.
        /// </summary>
		public IEconomy_InfoViewModel Economy_InfoViewModel
        {
            get { return _container.Resolve<Economy_InfoViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a Demographics_InfoViewModel.
        /// </summary>
		public IDemographics_InfoViewModel Demographics_InfoViewModel
        {
            get { return _container.Resolve<Demographics_InfoViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a FilmTelevision_InfoViewModel.
        /// </summary>
		public IFilmTelevision_InfoViewModel FilmTelevision_InfoViewModel
        {
            get { return _container.Resolve<FilmTelevision_InfoViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a Education_InfoViewModel.
        /// </summary>
		public IEducation_InfoViewModel Education_InfoViewModel
        {
            get { return _container.Resolve<Education_InfoViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a Media_InfoViewModel.
        /// </summary>
		public IMedia_InfoViewModel Media_InfoViewModel
        {
            get { return _container.Resolve<Media_InfoViewModel>(); }
        }

        /// <summary>
        /// Gets the reference to a History_InfoViewModel.
        /// </summary>
		public IHistory_InfoViewModel History_InfoViewModel
        {
            get { return _container.Resolve<History_InfoViewModel>(); }
        }
    }
}
