// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   DataSource.tt
using System;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using WPAppStudio.Entities;
using WPAppStudio.Repositories.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// Demographics_Html data source.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public class Demographics : IDemographics 
    {        
        /// <summary>
        /// Retrieves the html content.
        /// </summary>
        /// <returns>A string with the content in html format.</returns>
        public string Get()
        {			
            return @"<div>Meerut City is the headquarters of Meerut district which, according to the 2011 census, has a population of around 3.4 million. The sex ratio in Meerut is 885, lower than the state average of 908; while the child sex ratio is 850, lower than the state average of 899. 14.16% of the population is under 6 years of age. The district has a density of 1347 persons/km 2. The overall literacy rate is 74.80%, higher than the state average of 69.72%.<br /><br /></div><div>According to the 2001 census, the city ranked 6th in terms of population density in Uttar Pradesh. The city also ranked 2nd in terms of population in NCR.[77] The city had an average literacy rate of 65.96%, higher than the national average of 64.8% and the state average of 57.36%. 16.66% of the population was under 6 years of age. The percentage of Muslim population was close to 32.5% (one of the largest among the cities of India at the time). It is the largest Muslim city in Uttar Pradesh. The city had a sex ratio of 871, lower than the state average of 898 and the national average of 933.<br /></div>";
        }
	}
}
