// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   DataSource.tt
using System;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using WPAppStudio.Entities;
using WPAppStudio.Repositories.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// Education_Html data source.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public class Education : IEducation 
    {        
        /// <summary>
        /// Retrieves the html content.
        /// </summary>
        /// <returns>A string with the content in html format.</returns>
        public string Get()
        {			
            return @"<div>Meerut is an education hub of Western Uttar Pradesh with four universities, approximately 50 engineering colleges, 23 management colleges, seven pharmacy colleges, four colleges offering hotel management, one college offering fashion design, over 150 academic colleges and over 50 schools. The city is home to Chaudhary Charan Singh University (formerly Meerut University), Sardar Vallabhbhai Patel University of Agriculture and Technology, Swami Vivekanand Subharti University and Shobhit University. The city has one government-run engineering college, Sir Chhotu Ram Institute of Engineering and Technology, which is a constituent college of Chaudhary Charan Singh University. The city also has St. John's Sr. Sec.School, which was established by Begum Samru and is over 130 years old.</div><div><br />The Indian Film and Television Institute is located at the western bypass of the city. The city has two medical colleges: Subharti Medical College and Lala Lajpat Rai Memorial Medical College. The city has many madrasahs which provide religious education as well as modern education with computer learning. The city also has coaching institutions for preparing students for entrance exams of engineering and medical fields. By the attempts of local jewellers and Zila Udyog Kendra, a jewel and gem training centre will soon be established in the city.</div>";
        }
	}
}
