// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   DataSource.tt
using System;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using WPAppStudio.Entities;
using WPAppStudio.Repositories.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// etymology_Html data source.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public class etymology : Ietymology 
    {        
        /// <summary>
        /// Retrieves the html content.
        /// </summary>
        /// <returns>A string with the content in html format.</returns>
        public string Get()
        {			
            return @"<p>The city may have derived its name from Maya Rashtra, the capital of the kingdom of Mayasura, Mandodari's father and Ravana's father-in-law. This name may have mutated to Mairashtra, Mai-dant-ka-khera, Mairaath and eventually Meerut.</p><p>According to another version, Maya(sura), being a distinguished architect, received from King Yudhisthira the land on which the city of Meerut now stands and he called this place Mayarashtra, a name which in the course of time became shortened to Meerut. Tradition also has it that the city formed a part of the dominions of Mahipala, the king of Indraprastha, and the word Meerut is associated with his name</p>";
        }
	}
}
