// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   DataSource.tt
using System;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using WPAppStudio.Entities;
using WPAppStudio.Repositories.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// film_Html data source.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public class film : Ifilm 
    {        
        /// <summary>
        /// Retrieves the html content.
        /// </summary>
        /// <returns>A string with the content in html format.</returns>
        public string Get()
        {			
            return @"<span>Meerut is home to a booming local film industry, which has a large following in Western Uttar Pradesh and Haryana. The films are usually folklore stories or comedies or localised versions of Bollywood hits.<br /></span><br />Notable people from Meerut in the film and television industry include Bharat Bhushan, Mandakini, Achint Kaur, Arun Govil, Kailash Kher, Chitrangada Singh, Vishal Bhardwaj and Deepti Bhatnagar.<br />";
        }
	}
}
