// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   DataSource.tt
using System;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using WPAppStudio.Entities;
using WPAppStudio.Repositories.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// Geography_Html data source.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public class Geography : IGeography 
    {        
        /// <summary>
        /// Retrieves the html content.
        /// </summary>
        /// <returns>A string with the content in html format.</returns>
        public string Get()
        {			
            return @"Meerut district lies between 28°57’ to 29°02’ North latitude and 77°40’ to 77°45’ East longitude in the Indo-Gangetic plains of India. It is bound on the north by Muzaffarnagar district, in the south by Bulandshahar district while Ghaziabad and Baghpat districts form the southern and western limits. The river Ganges forms the eastern boundary and separates the district from Moradabad district and Bijnor district. The Hindon forms the western boundary and separates the district from Baghpat. The ground is not rocky and there are no mountains. The soil is composed of pleistocene and sub-recent alluvial sediments transported and deposited by river action from the Himalayan region. These alluvial deposits are unconsolidated. Lithologically, sediments consist of clay, silt and fine to coarse sand.&amp;nbsp;Land is very fertile for growing crops, especially wheat, sugarcane and vegetables.&amp;nbsp;<br /><br />The city lies between the plains of the Ganges and those of the Yamuna. In area Meerut District covers 2,522 km2 (974 sq mi), which is larger than Delhi (Delhi covers an area of 1,484 km2 [573 sq mi]), but in population Meerut had population of 3,443,689, which is three times less than Delhi.<br />";
        }
	}
}
