// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   DataSource.tt
using System;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using WPAppStudio.Entities;
using WPAppStudio.Repositories.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// info_Html data source.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public class info : Iinfo 
    {        
        /// <summary>
        /// Retrieves the html content.
        /// </summary>
        /// <returns>A string with the content in html format.</returns>
        public string Get()
        {			
            return @"<div><b>Meerut (मेरठ)</b> is a city in the Indian state of Uttar Pradesh. The city lies 70 km (43 mi) northeast of the national capital New Delhi, and 453 km (281 mi) northwest of the state capital, Lucknow. It is the second largest city in the National Capital Region of India (the largest being Delhi), the 16th largest metropolitan area and (as of 2001) the 25th largest city in India. It ranked 292 in 2006 and is projected to rank 242 in 2020 in the list of largest cities and urban areas in the world. The city covers an area of about 172 km square&amp;amp;nbsp;while the total area is 198 km square, third largest in Uttar Pradesh after Kanpur and Lucknow. It has the 2nd largest army cantonment in the country. The city is one of the largest producers of sports goods, and the largest producer of musical instruments in India.The city is also an education hub in western Uttar Pradesh</div><div><b><br /></b></div><div>The city of Meerut is said to be associated with earliest traditions of the Hindus according to which Maya, the father-in-law of Ravana, founded this place which has, therefore, been call Maidant-ka-Khera. According to another version Maya, a distinguished architect, got from king Yudhishther the land on which the city of Meerut now stands and he called this place Mayrashtra, a name which in course of time became shortened to Meerut. Tradition are so has it that the district formed part of the dominions of Mahipal, king of Indraprashta and the word Meerut is associated with his name. The city also&amp;amp;nbsp;holds extensive importance for the Mutiny of the Bengal Army in the year 1857</div>";
        }
	}
}
