// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   DataSource.tt
using System;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using WPAppStudio.Entities;
using WPAppStudio.Repositories.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// media_Html data source.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public class media : Imedia 
    {        
        /// <summary>
        /// Retrieves the html content.
        /// </summary>
        /// <returns>A string with the content in html format.</returns>
        public string Get()
        {			
            return @"Meerut is becoming an important media center, as journalists from all over Uttar Pradesh and other Indian states are working in Meerut. As media centres are situated in Meerut, the city is getting a good amount of publicity on the national platform. The law and order situation has improved a lot in the recent past and media has had an important role to play in it. Radio stations shared with Delhi are Radio City 91.1 MHz, Big FM 92.7 MHz, Red FM 93.5 MHz, Radio One 94.3 MHz, Hit 95 (95 MHz), Radio Mirchi 98.3 MHz, AIR FM Rainbow 102.6 MHz, Meow FM 104.8 MHz, AIR FM Gold 106.4 MHz. <br><br>Radio IIMT (90.4 MHz)&amp;nbsp;is the only radio station located in the city. The Hindi-language daily newspapers Dainik Jagran, Amar Ujala, Dainik Hindustan, Janwani, National Duniya, DLA, I-Next are published from the city. The english language supplements HT City, Meerut with Hindustan Times and Meerut Plus with the Times of India are also published here. A fortnightly tabloid english Newspaper 'Pulse of Markets' promoting local businesses and The City Lifestyles, an English weekly newspaper are also published here.</br></br>";
        }
	}
}
