// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   DataSource.tt
using System;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using WPAppStudio.Entities;
using WPAppStudio.Repositories.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// monumentsCollection data source.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public class monumentsCollection : ImonumentsCollection 
    {
        private readonly ObservableCollection<monumentsCollectionSchema> _data = new ObservableCollection<monumentsCollectionSchema>
		{
          new monumentsCollectionSchema
            {
                Id= new Guid("12abb2b5-d044-411c-bd08-66293c96c176"),
                Title=@"Basilica of Our Lady of Graces",
                Subtitle=@"Roman Catholic Church in Sardhana",
                Image=@"..\Images\Item-ed8cf2ac-e0e3-4605-b301-56e8b989c585.jpg",
                Description=@"asilica of Our Lady of Graces, also known as Churches among the Churches, is dedicated to Virgin Mary. The Church was built by Begum Samru, a Muslim lady who married a European mercenary soldier Walter Reinhardt Sombre. Samru converted to Roman Catholicism in 1781 and adopted the name Joanna Nobilis. She is regarded as the only Catholic ruler in India, and ruled the Principality of Sardhana in 18th and 19th century. The Church is the largest in North India.

The architect of the Church was Antonio Reghellini, an Italian from the city of Vicenza. The Church is based upon St. Peter's Basilica in Rome with touch of Palladio and some Indian architectural influence. The altar and its surrounds are of marble set with coloured stones. Much of the rest of the interior is also in marble, and everything is of the very highest craftsmanship. It is illuminated from an octagon set in the dome, from which the sun streams in.",
			},
          new monumentsCollectionSchema
            {
                Id= new Guid("6582a177-3476-42e3-a7bf-ff6e3e30c27f"),
                Title=@"Ghanta Ghar",
                Subtitle=@"Clocktower",
                Image=@"..\Images\Item-d5461c44-66de-4bc5-bfd1-24dd1cd38bc8.jpg",
                Description=@"The Clock Tower is an ancient monument constructed by the British in 1914. It is constructed at the site of the old Shambhu Darwaza. The clock tower is around 400 m away from the Begum Bridge and is known as the Zero Mile Point.",
			},
          new monumentsCollectionSchema
            {
                Id= new Guid("70f3d412-1cd2-4329-8a11-ad1e69004ec5"),
                Title=@"Jain temples",
                Subtitle=@"Hastinapur",
                Image=@"..\Images\Item-5db79275-659e-4d6a-9cdb-44203d9dc9fb.jpg",
                Description=@"According to Jain tradition, Hastinapur was one of the earliest Indian cities like Ayodhya and Kashi and came into existence during the time of Rishabhadeva (the first tirthankara) whose grandson, Somaprabha, was the first ruler of the place. It is also said to be the birthplace of three Jain tirthankars, Shantinatha, Kunthunath and Arahanatha]",
			},
          new monumentsCollectionSchema
            {
                Id= new Guid("00c3207f-f347-48db-bd18-6f4f959780ef"),
                Title=@"Jama Masjid",
                Subtitle=@"[Insert subtitle here]",
                Image=@"..\Images\Item-b5da1cad-ac1f-4cdb-898d-6ad840845d8e.jpg",
                Description=@"Jama Masjid is the sacred mosque for the followers of Islam was built by the Wazir of Sultan Mahmud Ghaznavi, Hassan Mahdi, in the year 1019. Refurbished by the Mughal Emperor, Humayun, this mosque is supposed to be the first of its kind in the entire northern part of India. The tomb of Ghazi Sayyad Salar Masud, an Islamic saint was constructed by the first ruler of the Delhi Sultanate, Qutubuddin Aibak. It is a holy place and one of the best Meerut attractions where the travelers should pay a visit.",
			},
          new monumentsCollectionSchema
            {
                Id= new Guid("bc21159d-2f09-4b64-83b4-79b37b4a76f7"),
                Title=@"Shaheed Smarak",
                Subtitle=@"Martyr Memorial",
                Image=@"..\Images\Item-6a6b0000-cca6-435a-ae45-8cc3b7a0b930.jpg",
                Description=@"The memorial is a 30 metres (98 feet) high pillar of marble situated at Bhainsali. Functions are organised at the memorial around the national holidays of India. The memorial complex also houses the Government Freedom Struggle Museum which is dedicated to the first war of Indian independence.x",
			},
          new monumentsCollectionSchema
            {
                Id= new Guid("20367e78-a5a4-4e90-848c-adfb575c89ab"),
                Title=@"Shahi Eid Gaah",
                Subtitle=@"Eid Gaah",
                Image=@"..\Images\Item-a41c26d9-e58f-4a02-9065-24ab4c35cb53.jpg",
                Description=@"It was built by Nasir ud din Mahmud, the youngest son of Iltutmish, and the eighth Sultan of the Delhi Sultanate. It is about six hundred years old and has a capacity of about one lac people to offer prayers (Namaz) on Eid. There is Nakkashi on the walls of Eidgah which reflect the Sulatani Gulam era.",
			},
          new monumentsCollectionSchema
            {
                Id= new Guid("8051e8d6-bfc8-4a3e-aed5-8799568c0be6"),
                Title=@"Shahpeer's Mausoleum",
                Subtitle=@"Shahpeer ki dargah",
                Image=@"..\Images\Item-ae43c547-496b-434a-98f5-ba08ff113c38.jpg",
                Description=@"This is a Mughal mausoleum erected by the empress Nur Jahan in 1628 in honour of a local Muslim Hazrat Shahpeer. It is a red stone structure that was partly built and is incomplete till date.[111] The tomb is adorned by intricate nakashi (stone painting). There is no roof on the main tomb. People say that Shahpeer was the teacher of Mughal Emperor Jehangir. The tomb is listed by the Archaeological Survey of India as a national heritage monument. Shahpeer gate was built in 1829 by a local Jagirdar ""Raja Ji"".",
			},
          new monumentsCollectionSchema
            {
                Id= new Guid("8aeb8f3b-983f-494e-ae0b-54baaef70800"),
                Title=@"St. John's Church",
                Subtitle=@"Saint John the Baptist",
                Image=@"..\Images\Item-02d2f327-9bbc-4b47-9009-af220ce46d71.jpg",
                Description=@"his church was established by Chaplin Reverend Henry Fisher on behalf of the East India Company in 1819 in the cantonment area and was completed in 1822. It is considered one of the oldest churches in North India. The Church was dedicated to the people by Bishop Wilson. It has a seating capacity of 10,000 people. During the war of 1857, this church was the scene of heavy fighting between Indians and the British forces.

The parish church of St John the Baptist is the oldest church edifice in the northern half of India. It still houses a huge but non-functioning pipe organ, which employed manually operated bellows to supply the organ with air. The wooden pews and kneelers, brass eagle lectern, marble baptistry, and stained glass windows all date back nearly two centuries.",
			},
          new monumentsCollectionSchema
            {
                Id= new Guid("9eb8795c-1277-4da1-bb75-1e4ff95a7209"),
                Title=@"St. John's Church",
                Subtitle=@"Saint John the Baptist",
                Image=@"..\Images\Item-02d2f327-9bbc-4b47-9009-af220ce46d71.jpg",
                Description=@"his church was established by Chaplin Reverend Henry Fisher on behalf of the East India Company in 1819 in the cantonment area and was completed in 1822. It is considered one of the oldest churches in North India. The Church was dedicated to the people by Bishop Wilson. It has a seating capacity of 10,000 people. During the war of 1857, this church was the scene of heavy fighting between Indians and the British forces.

The parish church of St John the Baptist is the oldest church edifice in the northern half of India. It still houses a huge but non-functioning pipe organ, which employed manually operated bellows to supply the organ with air. The wooden pews and kneelers, brass eagle lectern, marble baptistry, and stained glass windows all date back nearly two centuries.",
			},
		};
	
		
        /// <summary>
        /// Retrieves the data from a static data source, in an observable collection of monumentsCollectionSchema items.
        /// </summary>
        /// <returns>An observable collection of monumentsCollectionSchema items.</returns>
        public ObservableCollection<monumentsCollectionSchema> GetData()
        {		
            return _data;
        }
		
		/// <summary>
        /// Retrieves the data from a static data source, filtered by a filter specification, in an observable collection of monumentsCollectionSchema items.
        /// </summary>
		/// <param name="filter">Filter operation specification</param>
        /// <returns>An observable collection of monumentsCollectionSchema items.</returns>
        public ObservableCollection<monumentsCollectionSchema> Search(FilterSpecification filter)
        {
            return Filter<monumentsCollectionSchema>.FilterCollection(filter, _data);
        }
	}
}
