// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   DataSource.tt
using System;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using WPAppStudio.Entities;
using WPAppStudio.Repositories.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// Mythology_Html data source.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public class Mythology : IMythology 
    {        
        /// <summary>
        /// Retrieves the html content.
        /// </summary>
        /// <returns>A string with the content in html format.</returns>
        public string Get()
        {			
            return @"<div>Meerut was founded as Mayarashtra (lit. Maya's country) by Maya, who was the father of Mandodari, Ravana's wife in the Ramayana. Meerut was the capital of Maya. Thus the city is also known as 'Ravan Ki Sasural' literally meaning ""Ravana's wife's home"".<br /><br /></div><div>In the Ramayana, Shravan Kumar carried his feeble parents on his shoulders to all the pilgrimage sites in India, but it is believed that when he passed through Meerut, he put down his parents for a while to rest and drink. It was here that Lord Rama's father, King Dasharatha, mistook Shravan Kumar for a deer and accidentally shot him dead with an arrow. Shravan Kumar's parents cursed the king that he too would suffer and die due to separation from his son as they died.</div>";
        }
	}
}
