// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   DataSource.tt
using System;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using WPAppStudio.Entities;
using WPAppStudio.Repositories.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// specialplacesCollection data source.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public class specialplacesCollection : IspecialplacesCollection 
    {
        private readonly ObservableCollection<specialplacesCollectionSchema> _data = new ObservableCollection<specialplacesCollectionSchema>
		{
          new specialplacesCollectionSchema
            {
                Id= new Guid("a73fa82f-d659-4bd8-94e2-30b2cc94f3d7"),
                Title=@"Army Tank",
                Subtitle=@"Tank Four-way Mall Road",
                Image=@"..\Images\Item-fe5322ab-7212-4579-8424-31527d83dab4.jpg",
                Description=@"Monument of India-Pakistan war and a budge of honor for Indian Army of the victory they claim over Pakistan in 1971-72.",
			},
          new specialplacesCollectionSchema
            {
                Id= new Guid("c876ffb2-749a-4dc1-baa7-9080d37175af"),
                Title=@"Augarnath Temple",
                Subtitle=@"Kalipaltan Mandir",
                Image=@"..\Images\Item-682a6bc2-92a5-4ee6-ab9c-bf5b7e5e38f4.jpg",
                Description=@"This temple (also known as Kalipaltan Mandir locally) is located at the site where the soldiers of the war of 1857 planned their operations. The temple also houses a memorial built to honour the martyrs of the revolt of 1857. The old temple has been replaced by a modern version.",
			},
          new specialplacesCollectionSchema
            {
                Id= new Guid("420f5bf8-7b91-4c85-8075-026ce550ac6c"),
                Title=@"Gandhi Bagh",
                Subtitle=@"Company Garden",
                Image=@"..\Images\Item-c805e414-0a95-4271-8596-8e6c8f44e36a.jpg",
                Description=@"This centrally located garden has a very beautiful and serene environment. Locally known as ""Company Garden"", it has been present since before independence, when it got renamed to its current name. It runs a musical fountain show every evening. Earlier, the garden used to have multiple entrances like the one shown on the right, which were always kept open, and there was no entry fee. But now, only one entrance is kept open and a ticketing system with nominal charges has been put in place.",
			},
          new specialplacesCollectionSchema
            {
                Id= new Guid("c096aaf6-2911-4d6f-b6da-cd757b62aaee"),
                Title=@"Parikshitgarh",
                Subtitle=@"Parichhatgarh",
                Image=@"..\Images\Item-ba8e5738-82e5-4697-b46b-84532483f18b.jpg",
                Description=@"This town in the past was the capital of King Parikshit, the grandson of Arjuna who ascended the throne of Hastinapur after the Pandavas decided to renounce the kingship. Raja Parikshit, due to a transient malfunctioning of his thinking process, incurred the wrath of 'samadhi-sthit' Sage Shamik by his stupid action of garlanding the sage with a dead serpent. He was accordingly cursed by the saint to die by snake bite. After his ordained death at the fangs of Takshak Naga, his son Janmejaya became King and held a great sacrifice to annihilate the Nagas out of the passionate feelings of revenge.",
			},
		};
	
		
        /// <summary>
        /// Retrieves the data from a static data source, in an observable collection of specialplacesCollectionSchema items.
        /// </summary>
        /// <returns>An observable collection of specialplacesCollectionSchema items.</returns>
        public ObservableCollection<specialplacesCollectionSchema> GetData()
        {		
            return _data;
        }
		
		/// <summary>
        /// Retrieves the data from a static data source, filtered by a filter specification, in an observable collection of specialplacesCollectionSchema items.
        /// </summary>
		/// <param name="filter">Filter operation specification</param>
        /// <returns>An observable collection of specialplacesCollectionSchema items.</returns>
        public ObservableCollection<specialplacesCollectionSchema> Search(FilterSpecification filter)
        {
            return Filter<specialplacesCollectionSchema>.FilterCollection(filter, _data);
        }
	}
}
