// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   DataSource.tt
using System;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using WPAppStudio.Entities;
using WPAppStudio.Repositories.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// travel_Html data source.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public class travel : Itravel 
    {        
        /// <summary>
        /// Retrieves the html content.
        /// </summary>
        /// <returns>A string with the content in html format.</returns>
        public string Get()
        {			
            return @"<p><b>Reach Meerut By Air</b></p><div>Delhi International airport is the nearest airport to Meerut. There are many flights that ply to and from this international airport, connecting it to all the major cities of the country and abroad. There are regular flights available from this airport and private cabs can be boarded from the airport to reach Meerut.<br /><br /><div><b>Reach Meerut By Road<br /></b><p>Meerut is connected to the cities like Delhi (70 km), Chandigarh (250 km), Kanpur (405 km), Varanasi (725 km), Jhansi(432 km) and Agra (267 km) through well laid down roads. Buses run by Uttar Pradesh State Road Transport provide convenient journey to the travelers and solve the query of how to reach Meerut.&amp;nbsp;</p><p><b>Reach Meerut By Train</b></p><p><span>Meerut Cantonment station lies on the busy Delhi-Dehradun line of the Northern Central Railways and is considered to be the best way to reach Meerut. There are regular train services that connect this city to all the major cities of the state and the country.</span></p></div></div>";
        }
	}
}
