// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   DataSource.tt
using System;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using WPAppStudio.Entities;
using WPAppStudio.Repositories.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// weather_Html data source.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public class weather : Iweather 
    {        
        /// <summary>
        /// Retrieves the html content.
        /// </summary>
        /// <returns>A string with the content in html format.</returns>
        public string Get()
        {			
            return @"<div>Meerut has a monsoon influenced humid subtropical climate characterised by very hot summers and cool winters. Summers last from early April to late June during and are extremely hot, with temperatures reaching 43 °C (109 °F). The monsoon arrives in late June and continues till the middle of September. Temperatures drop slightly, with plenty of cloud cover but with higher humidity. Temperatures rise again in October and the city then has a mild, dry winter season from late October to the middle of March Lowest temperature recorded is 0.5 °C (32.9 °F).[citation needed] Rainfall is about 80 cm to 100 cm per annum, which is suitable for growing crops. Most of the rainfall is received during the monsoon. Humidity varies from 30 to 100%. The city receives no snow.<br /><b><br />Summer Season in Meerut</b></div><div><br />The period between the months of March to June marks the summer season in the city of Meerut. Summers are generally hot with temperatures wandering in the mid 30 degrees and the extremes reach even the high of 40 degrees. This season should be avoided for travelling.</div><div><br /><b>Monsoon Season in Meerut</b></div><div><br />Monsoon lasts for four months from June to September and offer moderate showers in the beginning that changes to heavy rainfall in the latter months of the season. This season is generally humid.</div><div><br /><b>Winter Season in Meerut</b></div><div><br />Meerut experiences cold weather in the months of November to February, with the temperature ranging from 20 degrees to 30 degrees. This weather offers a scenic view of the surroundings and is considered to be the best time to visit Meerut.</div><span id=""_wysihtml5-undo"" class=""_wysihtml5-temp"" />";
        }
	}
}
