// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.Collections.ObjectModel;
using System.Windows.Input;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// info_Info ViewModel interface.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public interface Iinfo_InfoViewModel
    {		
        /// <summary>
        /// Gets/Sets the Currentinfo_InfoHtmlControl property.
        /// </summary>
		string Currentinfo_InfoHtmlControl { get; set; }

        /// <summary>
        /// Gets/Sets the Monuments_ListListControlCollection property.
        /// </summary>
		ObservableCollection<monumentsCollectionSchema> Monuments_ListListControlCollection { get; set; }

        /// <summary>
        /// Gets/Sets the Selectedmonuments_ListListControlCollection property.
        /// </summary>
		monumentsCollectionSchema Selectedmonuments_ListListControlCollection { get; set; }

        /// <summary>
        /// Gets/Sets the SpecialPlaces_ListListControlCollection property.
        /// </summary>
		ObservableCollection<specialplacesCollectionSchema> SpecialPlaces_ListListControlCollection { get; set; }

        /// <summary>
        /// Gets/Sets the SelectedSpecialPlaces_ListListControlCollection property.
        /// </summary>
		specialplacesCollectionSchema SelectedSpecialPlaces_ListListControlCollection { get; set; }

        /// <summary>
        /// Gets/Sets the PhotoAlbum_NewsListControlCollection property.
        /// </summary>
		ObservableCollection<RssSearchResult> PhotoAlbum_NewsListControlCollection { get; set; }

        /// <summary>
        /// Gets/Sets the SelectedPhotoAlbum_NewsListControlCollection property.
        /// </summary>
		RssSearchResult SelectedPhotoAlbum_NewsListControlCollection { get; set; }

        /// <summary>
        /// Gets/Sets the SelectedMenuSection_MenuMenuControl property.
        /// </summary>
		MenuItemData SelectedMenuSection_MenuMenuControl { get; set; }

        
        /// <summary>
        /// Gets the RefreshPhotoAlbum_NewsListControlCollection command.
        /// </summary>
		ICommand RefreshPhotoAlbum_NewsListControlCollection { get; }

        
        /// <summary>
        /// Gets the SetLockScreenCommand command.
        /// </summary>
		ICommand SetLockScreenCommand { get; }

	}
}
