// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.Collections.ObjectModel;
using System.Windows.Input;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// monuments_Detail ViewModel interface.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public interface Imonuments_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentmonumentsCollectionSchema property.
        /// </summary>
		monumentsCollectionSchema CurrentmonumentsCollectionSchema { get; set; }

        
        /// <summary>
        /// Gets the TextToSpeechmonuments_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechmonuments_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the TextToSpeechAboutThisPlaceStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechAboutThisPlaceStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the Sharemonuments_DetailStaticControlCommand command.
        /// </summary>
		ICommand Sharemonuments_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareAboutThisPlaceStaticControlCommand command.
        /// </summary>
		ICommand ShareAboutThisPlaceStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartmonuments_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartmonuments_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartAboutThisPlaceStaticControlCommand command.
        /// </summary>
		ICommand PinToStartAboutThisPlaceStaticControlCommand { get; }

	}
}
