// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.Collections.ObjectModel;
using System.Windows.Input;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// PhotoAlbum_Detail ViewModel interface.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public interface IPhotoAlbum_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentRssSearchResult property.
        /// </summary>
		RssSearchResult CurrentRssSearchResult { get; set; }

        
        /// <summary>
        /// Gets the TextToSpeechPhotoAlbum_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechPhotoAlbum_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the SharePhotoAlbum_DetailStaticControlCommand command.
        /// </summary>
		ICommand SharePhotoAlbum_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartPhotoAlbum_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartPhotoAlbum_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the GoToSourcePhotoAlbum_DetailStaticControlCommand command.
        /// </summary>
		ICommand GoToSourcePhotoAlbum_DetailStaticControlCommand { get; }

	}
}
