// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.Collections.ObjectModel;
using System.Windows.Input;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// SpecialPlaces_Detail ViewModel interface.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public interface ISpecialPlaces_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentspecialplacesCollectionSchema property.
        /// </summary>
		specialplacesCollectionSchema CurrentspecialplacesCollectionSchema { get; set; }

        
        /// <summary>
        /// Gets the TextToSpeechSpecialPlaces_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechSpecialPlaces_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the TextToSpeechAboutThisPlace1StaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechAboutThisPlace1StaticControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareSpecialPlaces_DetailStaticControlCommand command.
        /// </summary>
		ICommand ShareSpecialPlaces_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the ShareAboutThisPlace1StaticControlCommand command.
        /// </summary>
		ICommand ShareAboutThisPlace1StaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartSpecialPlaces_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartSpecialPlaces_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartAboutThisPlace1StaticControlCommand command.
        /// </summary>
		ICommand PinToStartAboutThisPlace1StaticControlCommand { get; }

	}
}
