// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   IViewModel.tt
using System.Collections.ObjectModel;
using System.Windows.Input;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// TravelToMeerut_Info ViewModel interface.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public interface ITravelToMeerut_InfoViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentTravelToMeerut_InfoHtmlControl property.
        /// </summary>
		string CurrentTravelToMeerut_InfoHtmlControl { get; set; }

	}
}
