// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ViewModel.tt
using System;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Windows.Input;
using WPAppStudio;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;
using WPAppStudio.Localization;
using WPAppStudio.Repositories;
using WPAppStudio.Services;
using WPAppStudio.Services.Interfaces;
using WPAppStudio.Shared;
using WPAppStudio.ViewModel.Base;
using WPAppStudio.ViewModel.Interfaces;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of Demographics_Info ViewModel.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public partial class Demographics_InfoViewModel : BindableBase, IDemographics_InfoViewModel
    {       

		private readonly IDialogService _dialogService;
		private readonly INavigationService _navigationService;
		private readonly IDemographics _demographics;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="Demographics_InfoViewModel" /> class.
        /// </summary>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="demographics">The Demographics.</param>
        public Demographics_InfoViewModel(IDialogService dialogService, INavigationService navigationService, IDemographics demographics)
        {
			_dialogService = dialogService;
			_navigationService = navigationService;
			_demographics = demographics;
        }
		

		private string _currentDemographics_InfoHtmlControl;

        /// <summary>
        /// CurrentDemographics_InfoHtmlControl property.
        /// </summary>		
        public string CurrentDemographics_InfoHtmlControl
        {
            get
            {
                if(_currentDemographics_InfoHtmlControl == null)
					_currentDemographics_InfoHtmlControl = _demographics.Get();
				return _currentDemographics_InfoHtmlControl;     
            }
            set
            {
                SetProperty(ref _currentDemographics_InfoHtmlControl, value);
            }
        }
    }
}
