// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ViewModel.tt
using System;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Windows.Input;
using WPAppStudio;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;
using WPAppStudio.Localization;
using WPAppStudio.Repositories;
using WPAppStudio.Services;
using WPAppStudio.Services.Interfaces;
using WPAppStudio.Shared;
using WPAppStudio.ViewModel.Base;
using WPAppStudio.ViewModel.Interfaces;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of Education_Info ViewModel.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public partial class Education_InfoViewModel : BindableBase, IEducation_InfoViewModel
    {       

		private readonly IDialogService _dialogService;
		private readonly INavigationService _navigationService;
		private readonly IEducation _education;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="Education_InfoViewModel" /> class.
        /// </summary>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="education">The Education.</param>
        public Education_InfoViewModel(IDialogService dialogService, INavigationService navigationService, IEducation education)
        {
			_dialogService = dialogService;
			_navigationService = navigationService;
			_education = education;
        }
		

		private string _currentEducation_InfoHtmlControl;

        /// <summary>
        /// CurrentEducation_InfoHtmlControl property.
        /// </summary>		
        public string CurrentEducation_InfoHtmlControl
        {
            get
            {
                if(_currentEducation_InfoHtmlControl == null)
					_currentEducation_InfoHtmlControl = _education.Get();
				return _currentEducation_InfoHtmlControl;     
            }
            set
            {
                SetProperty(ref _currentEducation_InfoHtmlControl, value);
            }
        }
    }
}
