// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ViewModel.tt
using System;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Windows.Input;
using WPAppStudio;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;
using WPAppStudio.Localization;
using WPAppStudio.Repositories;
using WPAppStudio.Services;
using WPAppStudio.Services.Interfaces;
using WPAppStudio.Shared;
using WPAppStudio.ViewModel.Base;
using WPAppStudio.ViewModel.Interfaces;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of FilmTelevision_Info ViewModel.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public partial class FilmTelevision_InfoViewModel : BindableBase, IFilmTelevision_InfoViewModel
    {       

		private readonly IDialogService _dialogService;
		private readonly INavigationService _navigationService;
		private readonly Ifilm _film;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="FilmTelevision_InfoViewModel" /> class.
        /// </summary>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="film">The Film.</param>
        public FilmTelevision_InfoViewModel(IDialogService dialogService, INavigationService navigationService, Ifilm film)
        {
			_dialogService = dialogService;
			_navigationService = navigationService;
			_film = film;
        }
		

		private string _currentFilmTelevision_InfoHtmlControl;

        /// <summary>
        /// CurrentFilmTelevision_InfoHtmlControl property.
        /// </summary>		
        public string CurrentFilmTelevision_InfoHtmlControl
        {
            get
            {
                if(_currentFilmTelevision_InfoHtmlControl == null)
					_currentFilmTelevision_InfoHtmlControl = _film.Get();
				return _currentFilmTelevision_InfoHtmlControl;     
            }
            set
            {
                SetProperty(ref _currentFilmTelevision_InfoHtmlControl, value);
            }
        }
    }
}
