// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ViewModel.tt
using System;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Windows.Input;
using WPAppStudio;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;
using WPAppStudio.Localization;
using WPAppStudio.Repositories;
using WPAppStudio.Services;
using WPAppStudio.Services.Interfaces;
using WPAppStudio.Shared;
using WPAppStudio.ViewModel.Base;
using WPAppStudio.ViewModel.Interfaces;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of Geography_Info ViewModel.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public partial class Geography_InfoViewModel : BindableBase, IGeography_InfoViewModel
    {       

		private readonly IDialogService _dialogService;
		private readonly INavigationService _navigationService;
		private readonly IGeography _geography;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="Geography_InfoViewModel" /> class.
        /// </summary>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="geography">The Geography.</param>
        public Geography_InfoViewModel(IDialogService dialogService, INavigationService navigationService, IGeography geography)
        {
			_dialogService = dialogService;
			_navigationService = navigationService;
			_geography = geography;
        }
		

		private string _currentGeography_InfoHtmlControl;

        /// <summary>
        /// CurrentGeography_InfoHtmlControl property.
        /// </summary>		
        public string CurrentGeography_InfoHtmlControl
        {
            get
            {
                if(_currentGeography_InfoHtmlControl == null)
					_currentGeography_InfoHtmlControl = _geography.Get();
				return _currentGeography_InfoHtmlControl;     
            }
            set
            {
                SetProperty(ref _currentGeography_InfoHtmlControl, value);
            }
        }
    }
}
