// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ViewModel.tt
using System;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Windows.Input;
using WPAppStudio;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;
using WPAppStudio.Localization;
using WPAppStudio.Repositories;
using WPAppStudio.Services;
using WPAppStudio.Services.Interfaces;
using WPAppStudio.Shared;
using WPAppStudio.ViewModel.Base;
using WPAppStudio.ViewModel.Interfaces;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of History_Info ViewModel.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public partial class History_InfoViewModel : BindableBase, IHistory_InfoViewModel
    {       

		private readonly IDialogService _dialogService;
		private readonly INavigationService _navigationService;
		private readonly IHistory _history;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="History_InfoViewModel" /> class.
        /// </summary>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="history">The History.</param>
        public History_InfoViewModel(IDialogService dialogService, INavigationService navigationService, IHistory history)
        {
			_dialogService = dialogService;
			_navigationService = navigationService;
			_history = history;
        }
		

		private string _currentHistory_InfoHtmlControl;

        /// <summary>
        /// CurrentHistory_InfoHtmlControl property.
        /// </summary>		
        public string CurrentHistory_InfoHtmlControl
        {
            get
            {
                if(_currentHistory_InfoHtmlControl == null)
					_currentHistory_InfoHtmlControl = _history.Get();
				return _currentHistory_InfoHtmlControl;     
            }
            set
            {
                SetProperty(ref _currentHistory_InfoHtmlControl, value);
            }
        }
    }
}
