// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ViewModel.tt
using System;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Windows.Input;
using WPAppStudio;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;
using WPAppStudio.Localization;
using WPAppStudio.Repositories;
using WPAppStudio.Services;
using WPAppStudio.Services.Interfaces;
using WPAppStudio.Shared;
using WPAppStudio.ViewModel.Base;
using WPAppStudio.ViewModel.Interfaces;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of info_Info ViewModel.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public partial class info_InfoViewModel : BindableBase, Iinfo_InfoViewModel
    {       

		private readonly IDialogService _dialogService;
		private readonly INavigationService _navigationService;
		private readonly ILockScreenService _lockScreenService;
		private readonly Iinfo _info;
		private readonly ImonumentsCollection _monumentsCollection;
		private readonly IspecialplacesCollection _specialplacesCollection;
		private readonly Ialbum _album;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="info_InfoViewModel" /> class.
        /// </summary>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="lockScreenService">The Lock Screen Service.</param>
        /// <param name="info">The Info.</param>
        /// <param name="monumentsCollection">The Monuments Collection.</param>
        /// <param name="specialplacesCollection">The Specialplaces Collection.</param>
        /// <param name="album">The Album.</param>
        public info_InfoViewModel(IDialogService dialogService, INavigationService navigationService, ILockScreenService lockScreenService, Iinfo info, ImonumentsCollection monumentsCollection, IspecialplacesCollection specialplacesCollection, Ialbum album)
        {
			_dialogService = dialogService;
			_navigationService = navigationService;
			_lockScreenService = lockScreenService;
			_info = info;
			_monumentsCollection = monumentsCollection;
			_specialplacesCollection = specialplacesCollection;
			_album = album;
        }
		

		private string _currentinfo_InfoHtmlControl;

        /// <summary>
        /// Currentinfo_InfoHtmlControl property.
        /// </summary>		
        public string Currentinfo_InfoHtmlControl
        {
            get
            {
                if(_currentinfo_InfoHtmlControl == null)
					_currentinfo_InfoHtmlControl = _info.Get();
				return _currentinfo_InfoHtmlControl;     
            }
            set
            {
                SetProperty(ref _currentinfo_InfoHtmlControl, value);
            }
        }

		private ObservableCollection<monumentsCollectionSchema> _monuments_ListListControlCollection;

        /// <summary>
        /// Monuments_ListListControlCollection property.
        /// </summary>		
        public ObservableCollection<monumentsCollectionSchema> Monuments_ListListControlCollection
        {
            get
            {
                if(_monuments_ListListControlCollection == null)
					_monuments_ListListControlCollection = _monumentsCollection.GetData();
				return _monuments_ListListControlCollection;     
            }
            set
            {
                SetProperty(ref _monuments_ListListControlCollection, value);
            }
        }

		private monumentsCollectionSchema _selectedmonuments_ListListControlCollection;

        /// <summary>
        /// Selectedmonuments_ListListControlCollection property.
        /// </summary>		
        public monumentsCollectionSchema Selectedmonuments_ListListControlCollection
        {
            get
            {
				return _selectedmonuments_ListListControlCollection;
            }
            set
            {
                _selectedmonuments_ListListControlCollection = value;
                if (value != null)
                    _navigationService.NavigateTo<Imonuments_DetailViewModel>(_selectedmonuments_ListListControlCollection);
            }
        }

		private ObservableCollection<specialplacesCollectionSchema> _specialPlaces_ListListControlCollection;

        /// <summary>
        /// SpecialPlaces_ListListControlCollection property.
        /// </summary>		
        public ObservableCollection<specialplacesCollectionSchema> SpecialPlaces_ListListControlCollection
        {
            get
            {
                if(_specialPlaces_ListListControlCollection == null)
					_specialPlaces_ListListControlCollection = _specialplacesCollection.GetData();
				return _specialPlaces_ListListControlCollection;     
            }
            set
            {
                SetProperty(ref _specialPlaces_ListListControlCollection, value);
            }
        }

		private specialplacesCollectionSchema _selectedSpecialPlaces_ListListControlCollection;

        /// <summary>
        /// SelectedSpecialPlaces_ListListControlCollection property.
        /// </summary>		
        public specialplacesCollectionSchema SelectedSpecialPlaces_ListListControlCollection
        {
            get
            {
				return _selectedSpecialPlaces_ListListControlCollection;
            }
            set
            {
                _selectedSpecialPlaces_ListListControlCollection = value;
                if (value != null)
                    _navigationService.NavigateTo<ISpecialPlaces_DetailViewModel>(_selectedSpecialPlaces_ListListControlCollection);
            }
        }

		private ObservableCollection<RssSearchResult> _photoAlbum_NewsListControlCollection;

        /// <summary>
        /// PhotoAlbum_NewsListControlCollection property.
        /// </summary>		
        public ObservableCollection<RssSearchResult> PhotoAlbum_NewsListControlCollection
        {
            get
            {
                if(_photoAlbum_NewsListControlCollection == null)
					RefreshPhotoAlbum_NewsListControlCollectionDelegate();
				return _photoAlbum_NewsListControlCollection;     
            }
            set
            {
                SetProperty(ref _photoAlbum_NewsListControlCollection, value);
            }
        }

		private RssSearchResult _selectedPhotoAlbum_NewsListControlCollection;

        /// <summary>
        /// SelectedPhotoAlbum_NewsListControlCollection property.
        /// </summary>		
        public RssSearchResult SelectedPhotoAlbum_NewsListControlCollection
        {
            get
            {
				return _selectedPhotoAlbum_NewsListControlCollection;
            }
            set
            {
                _selectedPhotoAlbum_NewsListControlCollection = value;
                if (value != null)
                    _navigationService.NavigateTo<IPhotoAlbum_DetailViewModel>(_selectedPhotoAlbum_NewsListControlCollection);
            }
        }

		private MenuItemData _selectedMenuSection_MenuMenuControl;

        /// <summary>
        /// SelectedMenuSection_MenuMenuControl property.
        /// </summary>		
        public MenuItemData SelectedMenuSection_MenuMenuControl
        {
            get
            {
				return _selectedMenuSection_MenuMenuControl;
            }
            set
            {
                _selectedMenuSection_MenuMenuControl = value;
                if (value != null)
                    _navigationService.NavigateTo(value);
            }
        }

        /// <summary>
        /// Delegate method for the RefreshPhotoAlbum_NewsListControlCollection command.
        /// </summary>
        public async void RefreshPhotoAlbum_NewsListControlCollectionDelegate(int pageNumber= 1) 
        {
			try
			{
				LoadingPhotoAlbum_NewsListControlCollection = true;
				PhotoAlbum_NewsListControlCollection = await _album.GetData();
			}
            catch (Exception ex)
            {
				PhotoAlbum_NewsListControlCollection = null;
		
                Debug.WriteLine(ex.ToString());
                _dialogService.Show(AppResources.rssError + Environment.NewLine + AppResources.TryAgain);
            }
            finally
            {
				LoadingPhotoAlbum_NewsListControlCollection = false;
			}
        }
		
		
        private bool _loadingPhotoAlbum_NewsListControlCollection;
		
        public bool LoadingPhotoAlbum_NewsListControlCollection
        {
            get { return _loadingPhotoAlbum_NewsListControlCollection; }
            set { SetProperty(ref _loadingPhotoAlbum_NewsListControlCollection, value); }
        }

        private ICommand _refreshPhotoAlbum_NewsListControlCollection;

        /// <summary>
        /// Gets the RefreshPhotoAlbum_NewsListControlCollection command.
        /// </summary>
        public ICommand RefreshPhotoAlbum_NewsListControlCollection
        {
            get { return _refreshPhotoAlbum_NewsListControlCollection = _refreshPhotoAlbum_NewsListControlCollection ?? new DelegateCommand<int>(RefreshPhotoAlbum_NewsListControlCollectionDelegate); }
        }

        /// <summary>
        /// Delegate method for the SetLockScreenCommand command.
        /// </summary>
        public  void SetLockScreenCommandDelegate() 
        {
	
				_lockScreenService.SetLockScreen("LockScreen-a4f8e94c-8c40-4bc4-b381-b41c3e7689f6.jpg");
        }
		

        private ICommand _setLockScreenCommand;

        /// <summary>
        /// Gets the SetLockScreenCommand command.
        /// </summary>
        public ICommand SetLockScreenCommand
        {
            get { return _setLockScreenCommand = _setLockScreenCommand ?? new DelegateCommand(SetLockScreenCommandDelegate); }
        }
    }
}
