// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ViewModel.tt
using System;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Windows.Input;
using WPAppStudio;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;
using WPAppStudio.Localization;
using WPAppStudio.Repositories;
using WPAppStudio.Services;
using WPAppStudio.Services.Interfaces;
using WPAppStudio.Shared;
using WPAppStudio.ViewModel.Base;
using WPAppStudio.ViewModel.Interfaces;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of Media_Info ViewModel.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public partial class Media_InfoViewModel : BindableBase, IMedia_InfoViewModel
    {       

		private readonly IDialogService _dialogService;
		private readonly INavigationService _navigationService;
		private readonly Imedia _media;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="Media_InfoViewModel" /> class.
        /// </summary>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="media">The Media.</param>
        public Media_InfoViewModel(IDialogService dialogService, INavigationService navigationService, Imedia media)
        {
			_dialogService = dialogService;
			_navigationService = navigationService;
			_media = media;
        }
		

		private string _currentMedia_InfoHtmlControl;

        /// <summary>
        /// CurrentMedia_InfoHtmlControl property.
        /// </summary>		
        public string CurrentMedia_InfoHtmlControl
        {
            get
            {
                if(_currentMedia_InfoHtmlControl == null)
					_currentMedia_InfoHtmlControl = _media.Get();
				return _currentMedia_InfoHtmlControl;     
            }
            set
            {
                SetProperty(ref _currentMedia_InfoHtmlControl, value);
            }
        }
    }
}
