// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ViewModel.tt
using System;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Windows.Input;
using WPAppStudio;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;
using WPAppStudio.Localization;
using WPAppStudio.Repositories;
using WPAppStudio.Services;
using WPAppStudio.Services.Interfaces;
using WPAppStudio.Shared;
using WPAppStudio.ViewModel.Base;
using WPAppStudio.ViewModel.Interfaces;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of Mythology_Info ViewModel.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public partial class Mythology_InfoViewModel : BindableBase, IMythology_InfoViewModel
    {       

		private readonly IDialogService _dialogService;
		private readonly INavigationService _navigationService;
		private readonly IMythology _mythology;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="Mythology_InfoViewModel" /> class.
        /// </summary>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="mythology">The Mythology.</param>
        public Mythology_InfoViewModel(IDialogService dialogService, INavigationService navigationService, IMythology mythology)
        {
			_dialogService = dialogService;
			_navigationService = navigationService;
			_mythology = mythology;
        }
		

		private string _currentMythology_InfoHtmlControl;

        /// <summary>
        /// CurrentMythology_InfoHtmlControl property.
        /// </summary>		
        public string CurrentMythology_InfoHtmlControl
        {
            get
            {
                if(_currentMythology_InfoHtmlControl == null)
					_currentMythology_InfoHtmlControl = _mythology.Get();
				return _currentMythology_InfoHtmlControl;     
            }
            set
            {
                SetProperty(ref _currentMythology_InfoHtmlControl, value);
            }
        }
    }
}
