// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ViewModel.tt
using System;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Windows.Input;
using WPAppStudio;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;
using WPAppStudio.Localization;
using WPAppStudio.Repositories;
using WPAppStudio.Services;
using WPAppStudio.Services.Interfaces;
using WPAppStudio.Shared;
using WPAppStudio.ViewModel.Base;
using WPAppStudio.ViewModel.Interfaces;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of SpecialPlaces_Detail ViewModel.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public partial class SpecialPlaces_DetailViewModel : BindableBase, ISpecialPlaces_DetailViewModel, INavigable
    {       

		private readonly IDialogService _dialogService;
		private readonly INavigationService _navigationService;
		private readonly ISpeechService _speechService;
		private readonly IShareService _shareService;
		private readonly ILiveTileService _liveTileService;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="SpecialPlaces_DetailViewModel" /> class.
        /// </summary>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="speechService">The Speech Service.</param>
        /// <param name="shareService">The Share Service.</param>
        /// <param name="liveTileService">The Live Tile Service.</param>
        public SpecialPlaces_DetailViewModel(IDialogService dialogService, INavigationService navigationService, ISpeechService speechService, IShareService shareService, ILiveTileService liveTileService)
        {
			_dialogService = dialogService;
			_navigationService = navigationService;
			_speechService = speechService;
			_shareService = shareService;
			_liveTileService = liveTileService;
        }
		

		private specialplacesCollectionSchema _currentspecialplacesCollectionSchema;

        /// <summary>
        /// CurrentspecialplacesCollectionSchema property.
        /// </summary>		
        public specialplacesCollectionSchema CurrentspecialplacesCollectionSchema
        {
            get
            {
				return _currentspecialplacesCollectionSchema;
            }
            set
            {
                SetProperty(ref _currentspecialplacesCollectionSchema, value);
            }
        }

        /// <summary>
        /// Delegate method for the TextToSpeechSpecialPlaces_DetailStaticControlCommand command.
        /// </summary>
        public  void TextToSpeechSpecialPlaces_DetailStaticControlCommandDelegate() 
        {
	
				_speechService.TextToSpeech(CurrentspecialplacesCollectionSchema.Subtitle);
        }
		

        private ICommand _textToSpeechSpecialPlaces_DetailStaticControlCommand;

        /// <summary>
        /// Gets the TextToSpeechSpecialPlaces_DetailStaticControlCommand command.
        /// </summary>
        public ICommand TextToSpeechSpecialPlaces_DetailStaticControlCommand
        {
            get { return _textToSpeechSpecialPlaces_DetailStaticControlCommand = _textToSpeechSpecialPlaces_DetailStaticControlCommand ?? new DelegateCommand(TextToSpeechSpecialPlaces_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the TextToSpeechAboutThisPlace1StaticControlCommand command.
        /// </summary>
        public  void TextToSpeechAboutThisPlace1StaticControlCommandDelegate() 
        {
	
				_speechService.TextToSpeech(CurrentspecialplacesCollectionSchema.Description + " " + CurrentspecialplacesCollectionSchema.Description);
        }
		

        private ICommand _textToSpeechAboutThisPlace1StaticControlCommand;

        /// <summary>
        /// Gets the TextToSpeechAboutThisPlace1StaticControlCommand command.
        /// </summary>
        public ICommand TextToSpeechAboutThisPlace1StaticControlCommand
        {
            get { return _textToSpeechAboutThisPlace1StaticControlCommand = _textToSpeechAboutThisPlace1StaticControlCommand ?? new DelegateCommand(TextToSpeechAboutThisPlace1StaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the ShareSpecialPlaces_DetailStaticControlCommand command.
        /// </summary>
        public  void ShareSpecialPlaces_DetailStaticControlCommandDelegate() 
        {
	
				_shareService.Share(CurrentspecialplacesCollectionSchema.Subtitle, " ");
        }
		

        private ICommand _shareSpecialPlaces_DetailStaticControlCommand;

        /// <summary>
        /// Gets the ShareSpecialPlaces_DetailStaticControlCommand command.
        /// </summary>
        public ICommand ShareSpecialPlaces_DetailStaticControlCommand
        {
            get { return _shareSpecialPlaces_DetailStaticControlCommand = _shareSpecialPlaces_DetailStaticControlCommand ?? new DelegateCommand(ShareSpecialPlaces_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the ShareAboutThisPlace1StaticControlCommand command.
        /// </summary>
        public  void ShareAboutThisPlace1StaticControlCommandDelegate() 
        {
	
				_shareService.Share(CurrentspecialplacesCollectionSchema.Description, CurrentspecialplacesCollectionSchema.Description);
        }
		

        private ICommand _shareAboutThisPlace1StaticControlCommand;

        /// <summary>
        /// Gets the ShareAboutThisPlace1StaticControlCommand command.
        /// </summary>
        public ICommand ShareAboutThisPlace1StaticControlCommand
        {
            get { return _shareAboutThisPlace1StaticControlCommand = _shareAboutThisPlace1StaticControlCommand ?? new DelegateCommand(ShareAboutThisPlace1StaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the PinToStartSpecialPlaces_DetailStaticControlCommand command.
        /// </summary>
        public  void PinToStartSpecialPlaces_DetailStaticControlCommandDelegate() 
        {
	
				_liveTileService.PinToStart(typeof(ISpecialPlaces_DetailViewModel), CreateTileInfoSpecialPlaces_DetailStaticControl());
        }
		

        private ICommand _pinToStartSpecialPlaces_DetailStaticControlCommand;

        /// <summary>
        /// Gets the PinToStartSpecialPlaces_DetailStaticControlCommand command.
        /// </summary>
        public ICommand PinToStartSpecialPlaces_DetailStaticControlCommand
        {
            get { return _pinToStartSpecialPlaces_DetailStaticControlCommand = _pinToStartSpecialPlaces_DetailStaticControlCommand ?? new DelegateCommand(PinToStartSpecialPlaces_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the PinToStartAboutThisPlace1StaticControlCommand command.
        /// </summary>
        public  void PinToStartAboutThisPlace1StaticControlCommandDelegate() 
        {
	
				_liveTileService.PinToStart(typeof(ISpecialPlaces_DetailViewModel), CreateTileInfoAboutThisPlace1StaticControl());
        }
		

        private ICommand _pinToStartAboutThisPlace1StaticControlCommand;

        /// <summary>
        /// Gets the PinToStartAboutThisPlace1StaticControlCommand command.
        /// </summary>
        public ICommand PinToStartAboutThisPlace1StaticControlCommand
        {
            get { return _pinToStartAboutThisPlace1StaticControlCommand = _pinToStartAboutThisPlace1StaticControlCommand ?? new DelegateCommand(PinToStartAboutThisPlace1StaticControlCommandDelegate); }
        }
		public object NavigationContext
        {
            set
            {              
                if (!(value is specialplacesCollectionSchema)) { return; }
                
                CurrentspecialplacesCollectionSchema = value as specialplacesCollectionSchema;
            }
        }
        /// <summary>
        /// Initializes a <see cref="TileInfo" /> object for the SpecialPlaces_DetailStaticControl control.
        /// </summary>
		/// <returns>A <see cref="TileInfo" /> object.</returns>
        public TileInfo CreateTileInfoSpecialPlaces_DetailStaticControl()
        {
            var tileInfo = new TileInfo
            {
                CurrentId = CurrentspecialplacesCollectionSchema.Id.ToString(),
                Title = CurrentspecialplacesCollectionSchema.Subtitle,
                BackTitle = CurrentspecialplacesCollectionSchema.Subtitle,
                BackContent = string.Empty,
                Count = 0,
                BackgroundImagePath = CurrentspecialplacesCollectionSchema.Image,
                BackBackgroundImagePath = CurrentspecialplacesCollectionSchema.Image,
                LogoPath = "Logo-01a40c2e-7820-4d8b-864d-12a1eec805ac.png"
            };
            return tileInfo;
        }
        /// <summary>
        /// Initializes a <see cref="TileInfo" /> object for the AboutThisPlace1StaticControl control.
        /// </summary>
		/// <returns>A <see cref="TileInfo" /> object.</returns>
        public TileInfo CreateTileInfoAboutThisPlace1StaticControl()
        {
            var tileInfo = new TileInfo
            {
                CurrentId = CurrentspecialplacesCollectionSchema.Id.ToString(),
                Title = CurrentspecialplacesCollectionSchema.Description,
                BackTitle = CurrentspecialplacesCollectionSchema.Description,
                BackContent = CurrentspecialplacesCollectionSchema.Description,
                Count = 0,
                BackgroundImagePath = string.Empty,
                BackBackgroundImagePath = string.Empty,
                LogoPath = "Logo-01a40c2e-7820-4d8b-864d-12a1eec805ac.png"
            };
            return tileInfo;
        }
    }
}
