// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ViewModel.tt
using System;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Windows.Input;
using WPAppStudio;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;
using WPAppStudio.Localization;
using WPAppStudio.Repositories;
using WPAppStudio.Services;
using WPAppStudio.Services.Interfaces;
using WPAppStudio.Shared;
using WPAppStudio.ViewModel.Base;
using WPAppStudio.ViewModel.Interfaces;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of TravelToMeerut_Info ViewModel.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public partial class TravelToMeerut_InfoViewModel : BindableBase, ITravelToMeerut_InfoViewModel
    {       

		private readonly IDialogService _dialogService;
		private readonly INavigationService _navigationService;
		private readonly Itravel _travel;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="TravelToMeerut_InfoViewModel" /> class.
        /// </summary>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="travel">The Travel.</param>
        public TravelToMeerut_InfoViewModel(IDialogService dialogService, INavigationService navigationService, Itravel travel)
        {
			_dialogService = dialogService;
			_navigationService = navigationService;
			_travel = travel;
        }
		

		private string _currentTravelToMeerut_InfoHtmlControl;

        /// <summary>
        /// CurrentTravelToMeerut_InfoHtmlControl property.
        /// </summary>		
        public string CurrentTravelToMeerut_InfoHtmlControl
        {
            get
            {
                if(_currentTravelToMeerut_InfoHtmlControl == null)
					_currentTravelToMeerut_InfoHtmlControl = _travel.Get();
				return _currentTravelToMeerut_InfoHtmlControl;     
            }
            set
            {
                SetProperty(ref _currentTravelToMeerut_InfoHtmlControl, value);
            }
        }
    }
}
