// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   ViewModel.tt
using System;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Windows.Input;
using WPAppStudio;
using WPAppStudio.Controls;
using WPAppStudio.Entities;
using WPAppStudio.Entities.Base;
using WPAppStudio.Localization;
using WPAppStudio.Repositories;
using WPAppStudio.Services;
using WPAppStudio.Services.Interfaces;
using WPAppStudio.Shared;
using WPAppStudio.ViewModel.Base;
using WPAppStudio.ViewModel.Interfaces;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of Weather_Info ViewModel.
    /// </summary>
    [System.Runtime.CompilerServices.CompilerGenerated]
    [System.CodeDom.Compiler.GeneratedCode("Radarc", "4.0")]
    public partial class Weather_InfoViewModel : BindableBase, IWeather_InfoViewModel
    {       

		private readonly IDialogService _dialogService;
		private readonly INavigationService _navigationService;
		private readonly Iweather _weather;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="Weather_InfoViewModel" /> class.
        /// </summary>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="weather">The Weather.</param>
        public Weather_InfoViewModel(IDialogService dialogService, INavigationService navigationService, Iweather weather)
        {
			_dialogService = dialogService;
			_navigationService = navigationService;
			_weather = weather;
        }
		

		private string _currentWeather_InfoHtmlControl;

        /// <summary>
        /// CurrentWeather_InfoHtmlControl property.
        /// </summary>		
        public string CurrentWeather_InfoHtmlControl
        {
            get
            {
                if(_currentWeather_InfoHtmlControl == null)
					_currentWeather_InfoHtmlControl = _weather.Get();
				return _currentWeather_InfoHtmlControl;     
            }
            set
            {
                SetProperty(ref _currentWeather_InfoHtmlControl, value);
            }
        }
    }
}
